version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:{{cookiecutter.python_version}}

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python{{cookiecutter.python_version}}/site-packages
      - restore_cache:
          key: requirements_1-{{ "{{" }} .Branch {{ "}}" }}-{{ "{{" }} checksum "poetry.lock"{{ "}}" }}
      - run:
          command: |
            poetry install
      - save_cache:
          key: requirements_1-{{ "{{" }} .Branch{{ "}}" }}-{{ "{{" }} checksum "poetry.lock"{{ "}}" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: run tests
          command: |
            poetry run pytest -vv
      - run:
          name: coverage report
          command: |
            poetry run pytest -vv --cov={{cookiecutter.project_name}} test/
      - run:
          name: generate coverage reports
          command: poetry run coverage html -d artifacts
      - store_artifacts:
          path: artifacts
          destination: cov
